package services

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"sync"

	"powercodedeck/version"
)

// CodexConfig is deliberately limited to the stable v2 app-server surface used
// by the deck. The wire shapes are generated by
// `codex app-server generate-json-schema --experimental`.
type CodexConfig struct {
	SessionID string
	Cwd       string
	Model     string
	Mode      string
	ResumeID  string
	Broker    *PermissionBroker
}

type codexRPCMessage struct {
	ID     json.RawMessage `json:"id,omitempty"`
	Method string          `json:"method,omitempty"`
	Params json.RawMessage `json:"params,omitempty"`
	Result json.RawMessage `json:"result,omitempty"`
	Error  json.RawMessage `json:"error,omitempty"`
}

type CodexDriver struct {
	cfg CodexConfig

	mu       sync.Mutex
	cmd      *exec.Cmd
	stdin    io.WriteCloser
	stopped  bool
	nextID   int64
	pending  map[string]chan codexRPCMessage
	threadID string
	turnID   string
	events   chan *StreamEvent
	done     chan struct{}
}

func NewCodexDriver(cfg CodexConfig) *CodexDriver {
	return &CodexDriver{
		cfg: cfg, pending: make(map[string]chan codexRPCMessage),
		events: make(chan *StreamEvent, 128), done: make(chan struct{}),
	}
}

func (d *CodexDriver) Start() error {
	bin := "codex"
	if resolved := findAgentCommand("codex"); resolved != "" {
		bin = resolved
	}
	cmd := exec.Command(bin, "app-server", "--stdio")
	cmd.Dir = d.cfg.Cwd
	locale := utf8Locale()
	cmd.Env = withAgentPath(append(os.Environ(), "LANG="+locale, "LC_ALL="+locale))
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return err
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	go io.Copy(io.Discard, stderr)
	if err := cmd.Start(); err != nil {
		return err
	}

	d.mu.Lock()
	d.cmd, d.stdin = cmd, stdin
	d.mu.Unlock()
	go d.readPump(stdout)

	if _, err := d.call("initialize", map[string]any{
		"clientInfo":   map[string]any{"name": version.AppName, "version": version.Version},
		"capabilities": map[string]any{"experimentalApi": true},
	}); err != nil {
		d.Stop()
		return fmt.Errorf("codex initialize: %w", err)
	}
	if err := d.notify("initialized", map[string]any{}); err != nil {
		d.Stop()
		return err
	}

	var result json.RawMessage
	if d.cfg.ResumeID != "" {
		result, err = d.call("thread/resume", d.threadParams(true))
	}
	if d.cfg.ResumeID == "" || err != nil {
		result, err = d.call("thread/start", d.threadParams(false))
	}
	if err != nil {
		d.Stop()
		return fmt.Errorf("codex thread start: %w", err)
	}
	var started struct {
		Thread struct {
			ID    string `json:"id"`
			Turns []struct {
				Items []json.RawMessage `json:"items"`
			} `json:"turns"`
		} `json:"thread"`
		Model string `json:"model"`
	}
	if err := json.Unmarshal(result, &started); err != nil || started.Thread.ID == "" {
		d.Stop()
		return fmt.Errorf("codex thread start: invalid response")
	}
	d.mu.Lock()
	d.threadID = started.Thread.ID
	d.mu.Unlock()
	d.emitSystem(started.Model)
	for _, turn := range started.Thread.Turns {
		for _, item := range turn.Items {
			d.emitItem(item, true)
		}
		d.events <- nativeResultEvent()
	}
	return nil
}

func (d *CodexDriver) threadParams(resume bool) map[string]any {
	p := map[string]any{"cwd": d.cfg.Cwd}
	if d.cfg.Model != "" {
		p["model"] = d.cfg.Model
	}
	switch d.cfg.Mode {
	case "plan":
		p["approvalPolicy"], p["sandbox"] = "never", "read-only"
	case "bypassPermissions":
		p["approvalPolicy"], p["sandbox"] = "never", "danger-full-access"
	default:
		p["approvalPolicy"], p["sandbox"] = "on-request", "workspace-write"
	}
	if resume {
		p["threadId"] = d.cfg.ResumeID
	}
	return p
}

func (d *CodexDriver) Send(text string) error {
	d.mu.Lock()
	threadID, stopped := d.threadID, d.stopped
	d.mu.Unlock()
	if threadID == "" || stopped {
		return fmt.Errorf("codex driver: session is not running")
	}
	result, err := d.call("turn/start", map[string]any{
		"threadId": threadID,
		"input":    []map[string]any{{"type": "text", "text": text}},
	})
	if err != nil {
		return err
	}
	var r struct {
		Turn struct {
			ID string `json:"id"`
		} `json:"turn"`
	}
	_ = json.Unmarshal(result, &r)
	d.mu.Lock()
	d.turnID = r.Turn.ID
	d.mu.Unlock()
	return nil
}

func (d *CodexDriver) Interrupt() error {
	d.mu.Lock()
	threadID, turnID := d.threadID, d.turnID
	d.mu.Unlock()
	if threadID == "" || turnID == "" {
		return fmt.Errorf("codex driver: no active turn")
	}
	_, err := d.call("turn/interrupt", map[string]any{"threadId": threadID, "turnId": turnID})
	return err
}

func (d *CodexDriver) ConversationID() string {
	d.mu.Lock()
	defer d.mu.Unlock()
	return d.threadID
}

func (d *CodexDriver) Events() <-chan *StreamEvent { return d.events }

func (d *CodexDriver) Stop() {
	d.mu.Lock()
	if d.stopped {
		d.mu.Unlock()
		return
	}
	d.stopped = true
	stdin, cmd := d.stdin, d.cmd
	d.mu.Unlock()
	if stdin != nil {
		_ = stdin.Close()
	}
	if cmd != nil && cmd.Process != nil {
		_ = cmd.Process.Kill()
	}
}

func (d *CodexDriver) call(method string, params any) (json.RawMessage, error) {
	d.mu.Lock()
	if d.stopped || d.stdin == nil {
		d.mu.Unlock()
		return nil, fmt.Errorf("codex driver: stopped")
	}
	d.nextID++
	n := d.nextID
	id := strconv.FormatInt(n, 10)
	ch := make(chan codexRPCMessage, 1)
	d.pending[id] = ch
	d.mu.Unlock()
	if err := d.write(map[string]any{"jsonrpc": "2.0", "id": n, "method": method, "params": params}); err != nil {
		d.mu.Lock()
		delete(d.pending, id)
		d.mu.Unlock()
		return nil, err
	}
	msg, ok := <-ch
	if !ok {
		return nil, fmt.Errorf("codex app-server exited")
	}
	if len(msg.Error) > 0 && string(msg.Error) != "null" {
		return nil, fmt.Errorf("%s", msg.Error)
	}
	return msg.Result, nil
}

func (d *CodexDriver) notify(method string, params any) error {
	return d.write(map[string]any{"jsonrpc": "2.0", "method": method, "params": params})
}

func (d *CodexDriver) write(v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.stdin == nil || d.stopped {
		return fmt.Errorf("codex driver: stopped")
	}
	_, err = d.stdin.Write(append(b, '\n'))
	return err
}

func (d *CodexDriver) readPump(stdout io.ReadCloser) {
	defer close(d.events)
	defer close(d.done)
	sc := bufio.NewScanner(stdout)
	sc.Buffer(make([]byte, 0, 64*1024), 32*1024*1024)
	for sc.Scan() {
		var msg codexRPCMessage
		if json.Unmarshal(sc.Bytes(), &msg) != nil {
			continue
		}
		if len(msg.ID) > 0 && msg.Method == "" {
			key := string(msg.ID)
			d.mu.Lock()
			ch := d.pending[key]
			delete(d.pending, key)
			d.mu.Unlock()
			if ch != nil {
				ch <- msg
				close(ch)
			}
			continue
		}
		if len(msg.ID) > 0 && msg.Method != "" {
			go d.handleRequest(msg)
			continue
		}
		d.handleNotification(msg.Method, msg.Params)
	}
	d.mu.Lock()
	for id, ch := range d.pending {
		close(ch)
		delete(d.pending, id)
	}
	cmd := d.cmd
	d.mu.Unlock()
	if cmd != nil {
		_ = cmd.Wait()
	}
}

func (d *CodexDriver) handleRequest(msg codexRPCMessage) {
	var p map[string]any
	_ = json.Unmarshal(msg.Params, &p)
	itemID, _ := p["itemId"].(string)
	if itemID == "" {
		itemID = string(msg.ID)
	}
	input := map[string]any{"reason": p["reason"]}
	tool := "Codex"
	switch msg.Method {
	case "item/commandExecution/requestApproval":
		tool, input["command"], input["cwd"] = "Bash", p["command"], p["cwd"]
	case "item/fileChange/requestApproval":
		tool, input["path"] = "Edit", p["grantRoot"]
	default:
		d.respond(msg.ID, map[string]any{}, nil)
		return
	}
	raw, _ := json.Marshal(input)
	decision, err := d.cfg.Broker.Ask(PermissionRequest{
		ID: d.cfg.SessionID + ":" + itemID, SessionID: d.cfg.SessionID,
		ToolName: tool, Input: raw,
	}, d.done)
	if err != nil {
		d.respond(msg.ID, map[string]any{"decision": "cancel"}, nil)
		return
	}
	answer := "decline"
	if decision.Behavior == "allow" {
		answer = "accept"
	}
	d.respond(msg.ID, map[string]any{"decision": answer}, nil)
}

func (d *CodexDriver) respond(id json.RawMessage, result any, rpcErr any) {
	v := map[string]any{"jsonrpc": "2.0", "id": json.RawMessage(id)}
	if rpcErr != nil {
		v["error"] = rpcErr
	} else {
		v["result"] = result
	}
	_ = d.write(v)
}

func (d *CodexDriver) handleNotification(method string, raw json.RawMessage) {
	var p struct {
		ThreadID string          `json:"threadId"`
		Turn     json.RawMessage `json:"turn"`
		Item     json.RawMessage `json:"item"`
		Delta    string          `json:"delta"`
	}
	if json.Unmarshal(raw, &p) != nil {
		return
	}
	switch method {
	case "turn/started":
		var t struct {
			ID string `json:"id"`
		}
		_ = json.Unmarshal(p.Turn, &t)
		d.mu.Lock()
		d.turnID = t.ID
		d.mu.Unlock()
	case "item/started":
		d.emitItem(p.Item, false)
	case "item/completed":
		d.emitItem(p.Item, true)
	case "turn/completed":
		d.mu.Lock()
		d.turnID = ""
		d.mu.Unlock()
		d.events <- nativeResultEvent()
	}
}

func (d *CodexDriver) emitSystem(model string) {
	raw, _ := json.Marshal(map[string]any{
		"type": "system", "subtype": "init", "session_id": d.ConversationID(),
		"model": model, "cwd": d.cfg.Cwd, "claude_code_version": "Codex app-server",
		"mcp_servers": []map[string]string{{"name": "pcd", "status": "connected"}},
	})
	ev, _ := ParseStreamEvent(raw)
	d.events <- ev
}

func (d *CodexDriver) emitItem(raw json.RawMessage, completed bool) {
	var item struct {
		ID               string          `json:"id"`
		Type             string          `json:"type"`
		Text             string          `json:"text"`
		Command          string          `json:"command"`
		Cwd              string          `json:"cwd"`
		AggregatedOutput string          `json:"aggregatedOutput"`
		Changes          json.RawMessage `json:"changes"`
		Server           string          `json:"server"`
		Tool             string          `json:"tool"`
		Arguments        json.RawMessage `json:"arguments"`
		Result           json.RawMessage `json:"result"`
		Status           string          `json:"status"`
	}
	if json.Unmarshal(raw, &item) != nil {
		return
	}
	if item.Type == "agentMessage" {
		if completed && item.Text != "" {
			d.events <- nativeTextEvent("assistant", item.Text)
		}
		return
	}
	name := ""
	input := map[string]any{}
	output := ""
	switch item.Type {
	case "commandExecution":
		name, input["command"], input["cwd"], output = "Bash", item.Command, item.Cwd, item.AggregatedOutput
	case "fileChange":
		name, input["changes"] = "Edit", json.RawMessage(item.Changes)
		if completed {
			output = item.Status
		}
	case "mcpToolCall":
		name, input["server"], input["tool"], input["arguments"] = "MCP", item.Server, item.Tool, json.RawMessage(item.Arguments)
		if completed {
			output = string(item.Result)
		}
	default:
		return
	}
	var wire any
	if !completed {
		wire = map[string]any{"type": "assistant", "message": map[string]any{
			"role": "assistant", "content": []map[string]any{{"type": "tool_use", "id": item.ID, "name": name, "input": input}},
		}}
	} else {
		wire = map[string]any{"type": "user", "message": map[string]any{
			"role": "user", "content": []map[string]any{{"type": "tool_result", "tool_use_id": item.ID, "content": output, "is_error": item.Status == "failed"}},
		}}
	}
	b, _ := json.Marshal(wire)
	ev, _ := ParseStreamEvent(b)
	d.events <- ev
}
